### ISSUE TITLE
Crash - [SKPaymentQueue defaultQueue]

### ISSUE THREAD

**Issue by taimur** [MediaflexPL/MFINAppPurchaseManager#1]
The Library has a crash at this line.

[[SKPaymentQueue defaultQueue] addPayment:payment];

The reason was there is no line to removeTransactionObserver. 
Please add this line to the file and commit it. I have added this line and it works like a charm - working Perfect.

-(void)dealloc
{
    [[SKPaymentQueue defaultQueue] removeTransactionObserver:self];
}

Thanks a lot !!

**Comment by jdarowski** [comment]
Hi,

thanks for the attention! I will most certainly update this ASAP.\
